name: Linux (OpenGL)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deps
      run: sudo apt install -y make clang libxinerama-dev libxrandr-dev libasound2-dev libxi-dev mesa-common-dev libgl-dev libxcursor-dev libvulkan-dev libgtk-3-dev libudev-dev
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Node.js
      run: git clone https://github.com/armory3d/nodejs_bin.git --depth 1
    - name: Compile
      run: nodejs_bin/node-linux64 armorcore/make -g opengl
    - name: Compile clang opengl
      run: cd armorcore && node Kinc/make.js -g opengl --compiler clang --compile
    - name: Strip
      run: cd armorcore/Deployment && strip ArmorPaint
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: armorcore/Deployment/ArmorPaint
        # Target file
        target: build/krom/ArmorPaint
    - name: Create artifac
      uses: actions/upload-artifact@v2
      with:
        name: ArmorPaint.zip
        path: build/krom
