name: Linux (Vulkan)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Node.js
      run: git clone https://github.com/armory3d/nodejs_bin.git --depth 1
    - name: Compile
      run: nodejs_bin/node-linux64 armorcore/make -g vulkan
    - name: Apply patch vulkan
      run: cd armorcore && git apply patch/vulkan_raytrace.diff --directory=Kinc
    - name: Clone libraries
      run: cd armorcore && git clone --recursive https://github.com/armory3d/glsl_to_spirv Libraries/glsl_to_spirv
    - name: Compile clang vulkan
      run: cd armorcore && node Kinc/make.js -g vulkan --compiler clang --compile
    - name: Strip
      run: cd armorcore/Deployment && strip ArmorPaint
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: armorcore/Deployment/ArmorPaint
        # Target file
        target: build/krom/ArmorPaint
    - name: Copy file
      uses: actions/upload-artifact@v2
      with:
        name: ArmorPaint.zip
        path: build/krom
