name: Linux (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libgtk-3-dev --yes --quiet
    - name: Deps
      run: sudo apt install -y make clang libxinerama-dev libxrandr-dev libasound2-dev libxi-dev mesa-common-dev libgl-dev libxcursor-dev libvulkan-dev libgtk-3-dev libudev-dev
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Clone krafix
      run: git clone --recursive https://github.com/armory3d/glsl_to_spirv armorcore/Libraries/glsl_to_spirv
    - name: Get apply
      run: git apply armorcore/patch/vulkan_raytrace.diff --directory=armorcore/Kinc
    - name: Compile
      run: armorcore/Kinc/make --from armorcore -g vulkan --compiler clang
    - name: Compile 2
      run: armorcore/Kinc/make --from armorcore -g vulkan --compiler clang --compile
    - name: Strip
      run: cd armorcore/Deployment && strip ArmorPaint
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: armorcore/Deployment/ArmorPaint
        # Target file
        target: build/krom/ArmorPaint
    - name: Create artifac
      uses: actions/upload-artifact@v2
      with:
        name: ArmorPaint
        path: build/krom
