name: Windows (Direct3D11)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Node.js
      run: git clone https://github.com/armory3d/nodejs_bin.git --depth 1
    - name: Compile
      run: nodejs_bin/node.exe armorcore/make -g direct3d11
    - name: Action 7z
      uses: edgarrc/action-7z@v1
      with:
        args: 7z e armorcore/v8\libraries\win32\release\v8_monolith.7z
    - name: patch Kinc
      run: cd armorcore; git apply patch/window_handling.diff --directory=Kinc
    - name: kinc
      run: cd armorcore; node Kinc/make.js -g direct3d11
